spring:
  rabbitmq:
    host: ${RABBIT_HOST:192.168.99.100}
    port: ${RABBIT_PORT:5672}
    password: ${RABBIT_USER:admin}
    username: ${RABBIT_PASSWORD:admin}
  application:
    name: user-preferences
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}/user_preferences?useSSL=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
swagger.base-package: ua.suprun.userpref.controller