security:
  oauth2:
    client:
      clientId: 730173275799-9oj97nb942n2d1rrbn0vfn11jq2ii4ah.apps.googleusercontent.com
      clientSecret: qlEVRboD4yQQ4ncg4BQrZLYc
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false

spring:
  rabbitmq:
    host: ${RABBIT_HOST:192.168.99.100}
    port: ${RABBIT_PORT:5672}
    password: ${RABBIT_USER:admin}
    username: ${RABBIT_PASSWORD:admin}
  application:
    name: getaway
server:
  port: 8000
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://root:root@localhost:8010/eureka/}
zuul:
  routes:
    user:
      path: /user/**
    film:
      path: /film/**
    user-films-edge:
      path: /user-films-edge/**

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 41000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic