spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/film_users?useSSL=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
  liquibase:
    change-log: classpath:db/changelog.xml
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 0
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://root:root@localhost:8000/eureka/