version: '3.1'
services:
  db:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
  health-dashboard:
    image: health-dashboard:${APP_VERSION}
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${ENV}
    ports:
    - 9100:9100
  turbine:
    image: turbine:${APP_VERSION}
    restart: always
    environment:
      EUREKA_DEFAULT_ZONE: ${EUREKA_DEFAULT_ZONE}
      SPRING_PROFILES_ACTIVE: ${ENV}
      RABBIT_HOST: ${RABBITMQ_HOST}
      RABBIT_PORT: ${RABBITMQ_PORT}
      RABBIT_USER: ${RABBITMQ_USER_NAME}
      RABBIT_PASSWORD: ${RABBITMQ_USER_PASSWORD}
    ports:
      - 9095:9095
    links:
      - rabbit
  discovery:
    image: discovery-server:${APP_VERSION}
    restart: always
    environment:
      EUREKA_DEFAULT_ZONE: ${EUREKA_DEFAULT_ZONE}
      SPRING_PROFILES_ACTIVE: ${ENV}
    ports:
      - 8010:8010
  getaway:
    image: getaway:${APP_VERSION}
    restart: always
    environment:
      EUREKA_DEFAULT_ZONE: ${EUREKA_DEFAULT_ZONE}
      SPRING_PROFILES_ACTIVE: ${ENV}
      TRACE_SERVER_URL: ${TRACE_SERVER_URL}
      RABBIT_HOST: ${RABBITMQ_HOST}
      RABBIT_PORT: ${RABBITMQ_PORT}
      RABBIT_USER: ${RABBITMQ_USER_NAME}
      RABBIT_PASSWORD: ${RABBITMQ_USER_PASSWORD}
    ports:
      - 8000:8000
    links:
      - discovery
      - zipkin
  films:
    image: films:${APP_VERSION}
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${ENV}
      DB_HOST: ${MYSQL_HOST}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_DEFAULT_ZONE: ${EUREKA_DEFAULT_ZONE}
      RABBIT_HOST: ${RABBITMQ_HOST}
      RABBIT_PORT: ${RABBITMQ_PORT}
      RABBIT_USER: ${RABBITMQ_USER_NAME}
      RABBIT_PASSWORD: ${RABBITMQ_USER_PASSWORD}
      TRACE_SERVER_URL: ${TRACE_SERVER_URL}
    links:
      - discovery
      - db
      - rabbit
      - zipkin
  user:
     image: user:${APP_VERSION}
     restart: always
     environment:
       SPRING_PROFILES_ACTIVE: ${ENV}
       DB_HOST: ${MYSQL_HOST}
       DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       EUREKA_DEFAULT_ZONE: ${EUREKA_DEFAULT_ZONE}
       TRACE_SERVER_URL: ${TRACE_SERVER_URL}
       RABBIT_HOST: ${RABBITMQ_HOST}
       RABBIT_PORT: ${RABBITMQ_PORT}
       RABBIT_USER: ${RABBITMQ_USER_NAME}
       RABBIT_PASSWORD: ${RABBITMQ_USER_PASSWORD}
     links:
       - discovery
       - db
       - zipkin
  user-preferences:
     image: user-preferences:${APP_VERSION}
     restart: always
     environment:
       SPRING_PROFILES_ACTIVE: ${ENV}
       DB_HOST: ${MYSQL_HOST}
       DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       EUREKA_DEFAULT_ZONE: ${EUREKA_DEFAULT_ZONE}
       TRACE_SERVER_URL: ${TRACE_SERVER_URL}
       RABBIT_HOST: ${RABBITMQ_HOST}
       RABBIT_PORT: ${RABBITMQ_PORT}
       RABBIT_USER: ${RABBITMQ_USER_NAME}
       RABBIT_PASSWORD: ${RABBITMQ_USER_PASSWORD}
     links:
       - discovery
       - db
       - zipkin
  user-films-edge:
     image: user-films-edge:${APP_VERSION}
     restart: always
     environment:
       SPRING_PROFILES_ACTIVE: ${ENV}
       EUREKA_DEFAULT_ZONE: ${EUREKA_DEFAULT_ZONE}
       RABBIT_HOST: ${RABBITMQ_HOST}
       RABBIT_PORT: ${RABBITMQ_PORT}
       RABBIT_USER: ${RABBITMQ_USER_NAME}
       RABBIT_PASSWORD: ${RABBITMQ_USER_PASSWORD}
       TRACE_SERVER_URL: ${TRACE_SERVER_URL}
     links:
       - discovery
       - rabbit
       - zipkin
  rabbit:
    image: "rabbitmq:${RABBITMQ_VERSION}"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER_NAME}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_USER_PASSWORD}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_USER_VHOST}"
    ports:
      - "15672:15672"
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
volumes:
  mysql:
    driver: local