spring:
  application:
    name: test1
server:
  port: 8091
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://root:root@localhost:8000/eureka/