spring:
  rabbitmq:
    host: ${RABBIT_HOST:192.168.99.100}
    port: ${RABBIT_PORT:5672}
    password: ${RABBIT_USER:admin}
    username: ${RABBIT_PASSWORD:admin}
  application:
    name: turbine
server:
  port: 9095

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://root:root@localhost:8010/eureka/}
#turbine:
#  aggregator:
#    clusterConfig: SAMPLE-HYSTRIX-AGGREGATE
#  appConfig: SAMPLE-HYSTRIX-AGGREGATE