spring:
  rabbitmq:
    host: ${RABBIT_HOST:192.168.99.100}
    port: ${RABBIT_PORT:5672}
    password: ${RABBIT_USER:admin}
    username: ${RABBIT_PASSWORD:admin}
  application:
    name: film
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}/film_films?useSSL=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
swagger.base-package: ua.suprun.films.controller.rest

application:
  amqp:
    get-films-by-id-queue-name: get-films-by-id
    get-films-by-id-exchange-name: get-films-by-id-exchange