version: '3.1'
services:
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
  discovery:
    image: discovery-server:latest
    restart: always
    environment:
      EUREKA_DEFAULT_ZONE: http://root:root@discovery:8010/eureka/
      LOGSTASH_HOST: logstash
    ports:
      - 8010:8010
    links:
      - logstash
  getaway:
    image: getaway:latest
    restart: always
    environment:
      EUREKA_DEFAULT_ZONE: http://root:root@discovery:8010/eureka/
      TRACE_SERVER_URL: zipkin:9411
      LOGSTASH_HOST: logstash
    ports:
      - 8000:8000
    links:
      - discovery
      - zipkin
      - logstash
  films:
    image: films
    restart: always
    environment:
      DB_HOST: db
      DB_PASSWORD: root
      EUREKA_DEFAULT_ZONE: http://root:root@discovery:8010/eureka/
      TRACE_SERVER_URL: zipkin:9411
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      RABBIT_USER: admin
      RABBIT_PASSWORD: admin
      LOGSTASH_HOST: logstash
    links:
      - discovery
      - zipkin
      - db
      - rabbit
      - logstash
  user:
     image: user:latest
     restart: always
     environment:
       DB_HOST: db
       DB_PASSWORD: root
       EUREKA_DEFAULT_ZONE: http://root:root@discovery:8010/eureka/
       TRACE_SERVER_URL: zipkin:9411
       LOGSTASH_HOST: logstash
     links:
       - discovery
       - zipkin
       - db
       - logstash
  user-preferences:
     image: user-preferences:latest
     restart: always
     environment:
       DB_HOST: db
       DB_PASSWORD: root
       EUREKA_DEFAULT_ZONE: http://root:root@discovery:8010/eureka/
       TRACE_SERVER_URL: zipkin:9411
       LOGSTASH_HOST: logstash
     links:
       - discovery
       - zipkin
       - db
       - logstash
  user-films-edge:
     image: user-films-edge:latest
     restart: always
     environment:
       EUREKA_DEFAULT_ZONE: http://root:root@discovery:8010/eureka/
       TRACE_SERVER_URL: zipkin:9411
       RABBIT_HOST: rabbit
       RABBIT_PORT: 5672
       RABBIT_USER: admin
       RABBIT_PASSWORD: admin
       LOGSTASH_HOST: logstash
     links:
       - discovery
       - zipkin
       - rabbit
       - logstash
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  # sudo sysctl -w vm.max_map_count=262144
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    environment:
       ELASTICSEARCH_URL: http://elastic:9200
    ports:
      - 5601:5601
    links:
      - elastic
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 6.6.1
    ports:
      - "4560:4560"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    links:
      - elastic
volumes:
  esdata:
    driver: local
  mysql:
    driver: local