Vagrant.configure("2") do |config|
  config.vm.box = "v0rtex/xenial64"
  config.vm.network "private_network", ip: "192.168.0.5"
  config.vm.network "forwarded_port", guest: 3306, host: 3307
  config.vm.network "forwarded_port", guest: 8010, host: 8010
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.hostname = "microservices"
  config.vm.provider "virtualbox" do |vb|
       vb.memory = "3000"
       vb.cpus = 1
  end
  config.vm.provision "shell", path: "shell/set-up.sh"
end