spring:
  rabbitmq:
    host: ${RABBIT_HOST:192.168.99.100}
    port: ${RABBIT_PORT:5672}
    password: ${RABBIT_USER:admin}
    username: ${RABBIT_PASSWORD:admin}
  application:
    name: user-films-edge
swagger.base-package: ua.suprun.userfilmsedge.controller

application:
  amqp:
    films:
      get-films-by-id-exchange-name: get-films-by-id-exchange