spring:
  rabbitmq:
    host: ${RABBIT_HOST:192.168.99.100}
    port: ${RABBIT_PORT:5672}
    password: ${RABBIT_USER:admin}
    username: ${RABBIT_PASSWORD:admin}
  application:
    name: user-films-edge
swagger.base-package: ua.suprun.userfilmsedge.controller

management:
  restart:
    enabled: true
  shutdown:
    enabled: true
  endpoints:
    web.exposure.include: hystrix.stream

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 45000
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic